name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python and Selenium (no-binary)
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-binary :all: selenium
          pip list  # List installed packages to verify

      - name: Install Chromium and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          echo "/usr/bin" >> $GITHUB_PATH

      - name: Run Selenium script
        run: |
          python selenium_test.py